### PR TITLE
Add specs

### PR DESCRIPTION
**Pull request by mnovelo**

### CODE REVIEW

**Review by anero — COMMENTED** [review]
Looks good! There seem to be a few rubocop offenses on `spec/lib/sidekiq/throttled/strategy_spec.rb`, would you mind fixing those? I can merge once the build passes locally.

**Comment by mnovelo** [comment]
Working on the rubocop offenses and should have the fixes up shortly

**Comment by mnovelo** [comment]
@anero refactored those specs and made sure rubocop offenses are fixed

**Review by anero — APPROVED** [review]
Awesome, thanks!

**Pull request merged**
